import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>LKUD</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full h-screen m-auto">
        <div className="h-full w-1/3 fixed bg-maroon-base overflow-x-hidden pt-5 font-montserrat">
          LKUD
        </div>
      </main>
    </div>
  );
}
